%% Import data from text file.
% Script for importing data from the following text file:
%
%    H:\Neural_Network\trainoutput.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/05 23:59:16

%% Initialize variables.
filename = 'F:\Neural_Network\trainoutput.csv';
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
output1089 = dataArray{:, 1};
output1056 = dataArray{:, 2};
output1189 = dataArray{:, 3};
output1156 = dataArray{:, 4};
output3089 = dataArray{:, 5};
output3056 = dataArray{:, 6};
output3189 = dataArray{:, 7};
output3156 = dataArray{:, 8};
output2089 = dataArray{:, 9};
output2056 = dataArray{:, 10};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
